language: generic 
#need super user permission
sudo: required
#required copy of docker
services:
  - docker

#build the container before test the container
before_install:
  - docker build -t test -f Dockerfile.dev .

script:
  - docker run -e CI=true anuarredza/simple-react-docker npm run test